### ISSUE TITLE
The endpoint for evaluating the utility of a defense is not available

### ISSUE THREAD

**Issue by s-zanella** [ethz-spylab/satml-llms-ctf-issues#1]
The rules describe an endpoint for evaluating defense utility:

> Defenders are encouraged to interact with the endpoint `/api/v1/defense/{id}/evaluate-utility`, which provides utility scores based on the performance of the MMLU benchmark.

However, the endpoint isn't documented at https://ctf.spylab.ai/docs. Authenticated POST requests to the endpoint with a valid defense id return a 403 status code with content `{"detail": "Not superuser"}`. 

```bash
curl -v -X 'POST' \
    "https://ctf.spylab.ai/api/v1/defense/${DEFENSE_ID}/evaluate-utility" \
    -H 'accept: application/json' \
    -H "X-API-Key: ${CTF_API_KEY}" \
    -d ''
```

When can we expect the endpoint to be available?

**Comment by dpaleka** [comment]
Sorry, we had some issues here. Sometime next week.

**Comment by s-zanella** [comment]
Thanks for the quick reply! No worries.
