### ISSUE TITLE
API and rules for checking the password

### ISSUE THREAD

**Issue by NivC** [ethz-spylab/satml-llms-ctf-issues#19]
Dear SPY Lab,

Thank you very much for organizing this competition!

A small question please:
What are the API and rules for checking the password?
Does the attacker have to give a correct password in the first try to qualify?
If not, how many tries does the attacker have?

Also, could you clarify please the part about "Anything that puts the secret completely out of scope"? (under filters goal and scope)

Best,
Niv.

**Comment by dpaleka** [comment]
Thanks for taking part in our competition!

> Also, could you clarify please the part about "Anything that puts the secret completely out of scope"? (under filters goal and scope)

The discussion in https://github.com/ethz-spylab/satml-llms-ctf-issues/issues/13 contains an example of a defense that is disallowed by rules in that section, including the rule you mention. 

> Does the attacker have to give a correct password in the first try to qualify?
If not, how many tries does the attacker have?

Here are the preliminary rules (blue means not determined yet):
<img width="666" alt="Screen Shot 2024-01-02 at 22 16 30" src="https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/22846867/de1ad116-9881-4b4f-a25f-6feab3df5aab">

We will publish the full attack rules and the API before the Attack phase commences. The main scientific merit of this competition is figuring out whether a utility-preserving defense (of the specified form) exists that is hard to break. 
Eliciting this via scoring mechanisms in the Attack phase is not completely straightforward, for various reasons. Our concerns are highly dependent on the number of good defenses submitted, so this part of the rules can only be fixed after the Defense phase deadline.

> What are the API and rules for checking the password?

I'm not sure what this means.

**Comment by NivC** [comment]
Thanks for the response!
Let's say I know the secret in one of 5 strings that I have. In that case, I know a lot about the right password, but I will still probably not get it correctly on the first try.
Please note that this number of tries is different from the number of interactions with the LLM.
Niv.

**Comment by dedeswim** [comment]
You will have limited a number of attempts > 1 to guess what the correct secret is, both for the reconnaissance and the evaluation phases

**Comment by NivC** [comment]
Thanks!
