### ISSUE TITLE
The endpoint to see the currently submitted defense returns a 422 error

### ISSUE THREAD

**Issue by s-zanella** [ethz-spylab/satml-llms-ctf-issues#2]
The endpoint to see the currently submitted defense (`/api/v1/defense/submitted`) returns a 422 error response. This happens regardless of whether there is submitted defense. E.g.,

```bash
curl -X 'GET' \
  'https://ctf.spylab.ai/api/v1/defense/submitted' \
   -H 'accept: application/json' \
   -H "X-API-Key: ${CTF_API_KEY}" \
```

```json
{
  "detail": [
    {
      "type": "value_error",
      "loc": [
        "path",
        "id"
      ],
      "msg": "Value error, Id must be of type PydanticObjectId",
      "input": "submitted",
      "ctx": {
        "error": {}
      },
      "url": "https://errors.pydantic.dev/2.4/v/value_error"
    }
  ]
}
```

**Comment by dedeswim** [comment]
Hi, thanks a lot for catching this too! I'm currently debugging this. For some reason this works if the endpoint accepts POST requests and I run a POST request, but it throws this error if the endpoint accepts GET requests and I make a GET request.

I hope I'll have a fix by early next week. Meanwhile, as a workaround, I suggest to use `/api/v1/defenses` and filter by `submitted=true`. I'm sorry this is not currently working!

**Comment by dedeswim** [comment]
Ok I tracked the issue down. I am going to fix this early next week, even if it will probably require renaming the endpoint.

**Comment by dedeswim** [comment]
I managed to find a quick fix actually. Let me know if the problem still persists, meanwhile, I'll close the issue!
