### ISSUE TITLE
Error: Can't Start New Thread

### ISSUE THREAD

**Issue by ShayanShamsi** [ethz-spylab/satml-llms-ctf-issues#22]
Whether I use the interface or the API, and whether I use my defenses or those of my team members, when I try to send a message to a chat I get the error "can't start new thread". I checked using both models and the issue persists through both. My teammates seem to be having the same problem. I can't quite figure out what is wrong. Can someone please help?

![cant-start-new-thread](https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/94790483/76f85339-f4cf-40b5-95bf-1144b45ee51c)

**Comment by dedeswim** [comment]
Hi! Thanks a lot for reporting this. I restarted the server and everything seems to be working now. I will keep the issue open in case this happens again.

**Comment by ShayanShamsi** [comment]
Hello! Everything seems to be working perfectly fine now. Thanks for the quick response!
