### ISSUE TITLE
About Attack Score Calculation

### ISSUE THREAD

**Issue by BXHQu** [ethz-spylab/satml-llms-ctf-issues#25]
Hi ethz-spylab:
      If I participate in a CTF match alone, will my attack score be less than that of a multi-player team?

**Comment by dedeswim** [comment]
Hi, one-person teams and multi-people teams are treated in the same way in all regards.

**Comment by BXHQu** [comment]
> Hi, one-person teams and multi-people teams are treated in the same way in all regards.
Hi,Thank you very much for your reply
