### ISSUE TITLE
Disallowing "\n" in python filter

### ISSUE THREAD

**Issue by TimVanhamme** [ethz-spylab/satml-llms-ctf-issues#26]
Dear competition organizers,
Is there a reason you are disallowing "\n" in the python filter?

For example the following does not work:
def f(chat_history: list[str], model_output: str, secret: str) -> str:
   return "\n"

**Comment by dedeswim** [comment]
Hi, thanks a lot for pointing this out. This is not intended and I am currently looking into a fix.

**Comment by dedeswim** [comment]
This should be fixed now. Feel free to reopen if it does not work
