### ISSUE TITLE
Python filter limited to 512 characters

### ISSUE THREAD

**Issue by TimVanhamme** [ethz-spylab/satml-llms-ctf-issues#27]
Dear competition organizers.
There is a character limit of 512 on the Python filter. According to the rules, the limit of 512 characters only applied to the defense prompt (if I'm not mistaken, of course). Can you please clarify? Does the 512-character limit also apply to the LLM filter?

Best regards
Tim

**Comment by dedeswim** [comment]
Hi, we forgot to mention this in the rules, but there is a 512 characters limit also to the LLM filter and the Python filter.
