### ISSUE TITLE
The endpoint to read a defense doesn't allow me to read defenses from other users in my team

### ISSUE THREAD

**Issue by s-zanella** [ethz-spylab/satml-llms-ctf-issues#3]
The endpoint to get the details of a defense (`/api/v1/defense/{id}`) returns a 403 error if the defense was created by another member of my team even though I can get the same details through the endpoint that lists all teams defenses (`/api/v1/defenses`), with the exception of whether the defense is currently submitted.

```bash
curl -X 'GET' \
  "https://ctf.spylab.ai/api/v1/defense/${DEFENSE_ID}" \
  -H 'accept: application/json' \
  -H "X-API-Key: ${CTF_API_KEY}"
```
```json
{
  "detail": "You don't have the permission to see this object."
}
```
Cannot read (403 error) a defense from another users in my team using `/api/v1/defense/{id}` though I can read it from the list of all defenses in my team using `/api/v1/defenses`

**Comment by dedeswim** [comment]
Hi, thanks a lot for catching this. Now you should be able to see your team members' defenses. Feel free to re-open if you still have issues
