### ISSUE TITLE
Contents of `chat_history`

### ISSUE THREAD

**Issue by s-zanella** [ethz-spylab/satml-llms-ctf-issues#31]
The contents of the `chat_history` parameter passed to a Python filter have changed with respect to the original API. They now include not only the user prompts and filtered assistant responses, but also unfiltered assistant responses and intermediate results after applying the first filter. I think this change might have been introduced at the time the "Debug defense" functionality was added to the web interface. Is this change intended?

**Comment by dedeswim** [comment]
No, this was not intended and we have just pushed a fix. Thanks for raising the issue

**Comment by dedeswim** [comment]
Hi, thanks a lot for pointing this out. This was indeed not intended, and made us realise about another bug, which we have now fixed. Please see our latest Google Group [announcement](https://groups.google.com/g/satml-2024-llms-ctf/c/0eEY7Ll3jwk/m/Ucyly1UQAgAJ?utm_medium=email&utm_source=footer).

Sorry for the inconvenience!

**Comment by s-zanella** [comment]
No worries. Thanks for the quick fix!
