### ISSUE TITLE
Issues about defense phase

### ISSUE THREAD

**Issue by erikziyunchi** [ethz-spylab/satml-llms-ctf-issues#32]
Hi there, 

We are encountering some issues with the defense phase:

1. We can’t see the defense that the other one of us have made.
2. We're experiencing an error when submitting our defense via the endpoint "/defense/{id}/submit”. The response is a JSON with “detail”: “Not Found”.

We've also emailed @dedeswim about the details of our user ids and one of the submission ids we've tried. Could you please advise us on how to resolve these issues or guide us through the correct process if we are missing something? Thanks a lot!

**Comment by dedeswim** [comment]
Hi!

- 1: Is it in the chat UI or through the API?
- 2: can you please provide the code you're running to submit the defense?

Best,

Edoardo

**Comment by erikziyunchi** [comment]
Thanks for the prompt response!

1. It was in the chat UI
2. We've tried both `https://ctf.spylab.ai/api/v1/defense/{id}/submit` and `https://ctf.spylab.ai/defense/{id}/submit`

**Comment by dedeswim** [comment]
I answered via email since some personal details are involved in the solution. Once we will understand exactly what went wrong I will provide an answer free of private information here if I think it could be useful for other people!

**Comment by kieranfraser** [comment]
Hi @dedeswim, I'm experiencing similar difficulties via:
- chat UI: `Unexpected token 'B', "Bad Gateway" is not valid JSON`
- API: `raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by dedeswim** [comment]
Hi, how long ago did this happen? I had to restart the server and this is the type of error you would get during server start-up. Can you please try again?

**Comment by kieranfraser** [comment]
> Hi @kieranfraser, how long ago did this happen? I had to restart the server and this is the type of error you would get during server start-up. Can you please try again?

Just this morning - had tested an hour ago. Can confirm it's now back online! Thanks @dedeswim :)
