### ISSUE TITLE
getting "Error can't start new thread" on both models

### ISSUE THREAD

**Issue by regoar** [ethz-spylab/satml-llms-ctf-issues#33]
Both Lama and GPT give the alert 'Error can't start new thread' in both the chat interface and evaluation utility. This happens for any defense (I tested it with a default minimal defense). I still have budget left. It started about ~1 hour ago.

**Comment by regoar** [comment]
Working fine now, thanks!

**Comment by epistoteles** [comment]
I am having the same problem right now

**Comment by dedeswim** [comment]
Should be back online
