### ISSUE TITLE
Failed to fetch error during /api/v1/defense/{id}/evaluate-utility

### ISSUE THREAD

**Issue by persistz** [ethz-spylab/satml-llms-ctf-issues#35]
When I use the API to perform the evaluate-utility operation, the browser has a certain probability of returning the following error, which causes a lot of budget waste.

Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.

**Comment by dedeswim** [comment]
Hi, the server was overloaded and I restarted it. There is likely a memory leak. Can you try again?

**Comment by persistz** [comment]
OK, thanks. I will try again and close the issue.

**Comment by persistz** [comment]
Hi Edoardo @dedeswim ,

I refresh the website and resent the corresponding post request, but the server still returned the same error.

Code | Details
-- | --
Undocumented | Failed to fetch. Possible Reasons: CORS Network Failure URL scheme must be "http" or "https" for CORS request.

**Comment by dedeswim** [comment]
Hi, can you please send what request you're sending? Remember to censor the API key

**Comment by persistz** [comment]
The request is:
```
curl -X 'POST' \
  'https://ctf.spylab.ai/api/v1/defense/xxxxx/evaluate-utility' \
  -H 'accept: application/json' \
  -H 'X-API-Key: xxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "api_keys": {
  },
  "model": "openai/gpt-3.5-turbo-1106",
  "small": true
}'
```

One detail is that even if the above error is returned, my account will be deducted (the amount of the deduction depends on how long the program is running), so this seems to be an error that occurred midway through the utility evaluation.

**Comment by dedeswim** [comment]
Can you please provide the defense ID? This won't be enough for competition participants to see your defense (they'll also need your API key)
