### ISSUE TITLE
Scoring value gamma

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#39]
![Screenshot from 2024-01-24 23-49-48](https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/20706203/fb140679-0971-4500-b514-1784a3696ca2)

0.95^7 = 0.698...
0.99^7 = 0.932...

Which of the two is it? Looks like this must be a mistake.

**Comment by dpaleka** [comment]
To be determined after counting the eligible defenses and the number of teams.

**Comment by dpaleka** [comment]
It's now in the rules (0.85)
