### ISSUE TITLE
Defense interface is not showing

### ISSUE THREAD

**Issue by sandervandorsten** [ethz-spylab/satml-llms-ctf-issues#40]
https://ctf.spylab.ai/defense/ is not showing a website

![image](https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/9109346/5f294475-d8a5-45fc-be35-76fd878fca91)

**Comment by dedeswim** [comment]
Hi! The defense phase finished yesterday. We're currently working on setting the website up for the attack phase that will start tomorrow anywhere on Earth
