### ISSUE TITLE
Some questions about attacks

### ISSUE THREAD

**Issue by BXHQu** [ethz-spylab/satml-llms-ctf-issues#41]
Hi:
    Today, I use "expamle_attack.py" to   Reconnaissance denfense. I have same questions：
       1. The rules do not specify how to get the target defense ID。
       2. An error occurred while using 'expamle-attack. py'。
       
![error_attack](https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/40231751/39b8b664-424b-4aad-bd29-38b3bfcb0f2e)

**Comment by dedeswim** [comment]
Hi, the attack phase has not started yet. There will be an API endpoint to get the list of submissions to attack.
