### ISSUE TITLE
How to get target_defense_id

### ISSUE THREAD

**Issue by BXHQu** [ethz-spylab/satml-llms-ctf-issues#42]
HI:
    I didn't participate in the defense submission, so I don't have my own defense ID. So how should I get a valid target defense ID for defense reconnaissance. Thanks!

**Comment by dankleeman** [comment]
You can get that through accessing the API endpoint called submission:

> [submission](https://ctf.spylab.ai/docs#/submission)
List submissions to attack. Submissions are shuffled in a different way for each team to prevent the same submissions to be attacked by everyone. 

https://ctf.spylab.ai/docs#/

**Comment by BXHQu** [comment]
> 您可以通过访问称为提交的 API 端点来获取此信息：
> 
> > [提交](https://ctf.spylab.ai/docs#/submission)
> > 列出要攻击的提交。每个团队的提交内容都会以不同的方式进行排序，以防止相同的提交内容受到每个团队的攻击。
> 
> https://ctf.spylab.ai/docs#/

Thank you very much for your reply. I'll give it a try.

**Comment by BXHQu** [comment]
Hi:
   How should I solve the following problem, thank you!
![image](https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/40231751/cc0d36e4-a504-436d-986f-adcc91ede04e)

**Comment by dedeswim** [comment]
Hi, this is likely because you're not part of a team. I made the error more explicit if this is the case. Can you please try again and send a screenshot of the error you get now?

**Comment by BXHQu** [comment]
> Hi, this is likely because you're not part of a team. I made the error more explicit if this is the case. Can you please try again and send a screenshot of the error you get now?

yes, The reason for my error was because I was not a member of the team. I had already submitted a team formation application to the organizing committee. I would like to know how long it will take for the application to be approved.

**Comment by dedeswim** [comment]
Hi, I added the teams now. Let me know if you still encounter this problem. Meanwhile, I will close the issue.
