### ISSUE TITLE
Cannot create attack chat

### ISSUE THREAD

**Issue by dankleeman** [ethz-spylab/satml-llms-ctf-issues#43]
I have been trying to follow the API documentation to create an attack chat but both in the documentation "Try it out" and when using the example code I get a 403 response 

```
{
  "detail": "Not superuser"
}
```

Is there an extra authentication step I need to take beyond supplying my API key to be able to create an attack chat and do recon?

**Comment by dedeswim** [comment]
Hi, my bad: I forgot to enable the endpoint for all users. It should be fixed now.

**Comment by TimVanhamme** [comment]
I have the same problem when requesting all attacks.
