### ISSUE TITLE
Error 403 when requesting all attacks

### ISSUE THREAD

**Issue by TimVanhamme** [ethz-spylab/satml-llms-ctf-issues#44]
Same problem as #43 but for different endpoint.

**Comment by dedeswim** [comment]
Can you please clarify which endpoint you are talking about?

**Comment by epistoteles** [comment]
It's the /chat/attacks endpoint. The error is 403: "detail": "Not superuser"

**Comment by dedeswim** [comment]
Thanks a lot, I found it and I am working on a fix. I may need to change the endpoint name.

**Comment by dedeswim** [comment]
The issue is solved now, but I had to rename the endpoint from `/chat/attacks` to `/chat/attack/`. Now it also takes a parameter `evaluation` to get only the `evaluation` chats once the evaluation phase will start. Sorry for the inconvenience!

**Comment by TimVanhamme** [comment]
Error is gone.
