### ISSUE TITLE
Defense template for everyone

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#45]
While the /attacks endpoint is down I made the effort to manually catalogue all defenses that made it to the attack phase:

https://docs.google.com/spreadsheets/d/1TKXkMdudzPgDAy5hZrb4beXOD_5TnSEHbaYY0WNuags/edit?usp=sharing

Feel free to make a copy of my template for yourself. It's really hard to keep track of all the models when you do some manual testing.

Happy attacking everyone!

**Comment by dedeswim** [comment]
Thanks a lot for this! We will advertise it with the next Google Group post.

**Comment by dedeswim** [comment]
I pinned it so that it's easily visible by everyone!

**Comment by epistoteles** [comment]
You might want to keep the issue open for a while if the goal is to make it more visible. Thx!

**Comment by dedeswim** [comment]
Sounds good!
