### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#46]
I remember the rules stating something about a leaderboard.

Will a leaderboard become visible only during the evaluation phase? Or can we also see the number of successful secret extractions in the evaluate=False setting? It would be nice to get a feel for the expected values of gamma shortly after the evaluation phase starts in advance.

Also, do you know the exact time when the evaluation phase will start on Feb 3rd? Since "being the first" is desirable for maximum points, it would be nice to allocate a time slot in my schedule when I can wait for the evaluate=True flag to be released.

**Comment by dedeswim** [comment]
Hi! Yes, a leaderboard will be up by the time the evaluation phase starts. Your other questions should be answered in the latest Google Group [post](https://groups.google.com/g/satml-2024-llms-ctf/c/hYsPeyfGIek).

Please let me know if you still have questions!
