### ISSUE TITLE
Did the available submissions change?

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#50]
Did you remove submissions from the competition?

For example, I can still interact with the RSLLM Llama submission via its ID (I saved it locally). Yet, when I query the submissions API, the model is no longer included in the response.

**Comment by dedeswim** [comment]
Please see my [comment](https://github.com/ethz-spylab/satml-llms-ctf-issues/discussions/48#discussioncomment-8326933) #48 for more info about this.

I have now also disabled creating chats with these submissions

**Comment by dedeswim** [comment]
https://github.com/ethz-spylab/satml-llms-ctf-issues/discussions/48#discussioncomment-8335587
