### ISSUE TITLE
API experiencing high latency at the moment

### ISSUE THREAD

**Issue by s-zanella** [ethz-spylab/satml-llms-ctf-issues#53]
I'm experiencing a very high latency in some API endpoints at the moment. For instance, requests to `/api/v1/chat/attack/create` consistently complete in over 3 minutes compared to seconds days ago. Understandably, the service must be under heavy load at the moment, but come tomorrow this will be even worse.

**Comment by s-zanella** [comment]
Duplicate of #52

**Comment by s-zanella** [comment]
Any API call is taking longer than 10 minutes at the moment.

**Comment by dedeswim** [comment]
Are these using which model?

**Comment by s-zanella** [comment]
Llama-2. But even API calls that don't trigger queries to Together AI are failing.

**Comment by s-zanella** [comment]
Nevermind, it's already past the deadline.

**Comment by dedeswim** [comment]
We apologise for the issues. We further increased the server capacity three days ago, hoping that it would have been enough to handle last minute submissions, but it clearly wasn't enough

**Comment by s-zanella** [comment]
No worries. I really appreciate all the effort you put into running the competition and that's not going to be tarnished by last minute issues. It was great fun! Thanks a lot!

**Comment by dedeswim** [comment]
Thank you for the participation, and congrats on the second place! We're happy you had fun!
