### ISSUE TITLE
20 instead of 200 bonus points?

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#56]
It seems that the bonus points are 20 right now instead of 200.

Will this be fixed?

If it will be fixed, I'll restart new chats now (1200 - 50 >> 1000). If it won't be fixed, I'll be more hesitant to restart new chats (1020 - 50 < 1000).

**Comment by dpaleka** [comment]
Does this hold if the total score is multiplied by the defense value (second column)?

**Comment by dpaleka** [comment]
<img width="648" alt="Screen Shot 2024-02-05 at 13 22 24" src="https://github.com/ethz-spylab/satml-llms-ctf-issues/assets/22846867/ffe23310-5d35-470f-bb11-10c88ff8dd07">

**Comment by epistoteles** [comment]
For some reason I though the maximum number of points one can get is 1200.
