### ISSUE TITLE
Submitting secret

### ISSUE THREAD

**Issue by jacoporepossi** [ethz-spylab/satml-llms-ctf-issues#57]
Hello there,

I'm facing an issue where I submitted a correct secret using the interactive API docs (using the secret_guess) but when I check the scores endpoint I can't see my score correctly populated. Furthermore, retrying the scores endpoint gives me a 304 response status.

Thank you

**Comment by dedeswim** [comment]
Hi, the scores are cached and updated every minute to prevent the server from being overloaded, so you have to wait at most 60 seconds to see your updated score.

**Comment by dedeswim** [comment]
I see that no scores from your team are not appearing yet. Are you sure that you're creating eval chats, as described in the API documentation and in the rules?

**Comment by jacoporepossi** [comment]
Actually, my bad.
I was using the interface to chat with a given defence. Whenever I was able to get the secret, I was copying the `secret_id` and `chat_id` in the API docs and using the `secret_guess` endpoint to submit the attack.

I'm aware the interface is in Reconnaissance mode (so `check the secret` doesn't count), but I didn't know the whole chat system couldn't work the way I just described.

**Comment by dedeswim** [comment]
We're sorry that we don't allow running evaluation phase stuff through the chat interface, but unfortunately, we believe that the UI library we are using for it is not reliable enough for this: it could send duplicate requests, or not send any at all, hence messing up with the numbers you would expect
