### ISSUE TITLE
[API support] List the chat id by defense

### ISSUE THREAD

**Issue by persistz** [ethz-spylab/satml-llms-ctf-issues#58]
Hi,

Could we add a API to support list/get the chat_id by defense?
Now we can only get the chat info and id by exhaustive or precise search. For a team with multiple members, it is difficult to record each chat id. I would like to be able to see if a teammate has a chat record on a certain defense.

Thanks.

**Comment by persistz** [comment]
> Just to clarify, you would like to get what chats have been created by you and your team members for a given defense submission?

Yes, I think this allows us to continue attacking on the chat created by my teammates without being -50 for creating new chat.

**Comment by dedeswim** [comment]
Ok, I will look into that, but we won't deploy anything for the next ~24 hours to prevent disrupting what we expect to be the busiest time for the eval phase. Meanwhile, please coordinate with your teammates to prevent double chats.

**Comment by persistz** [comment]
Thanks. BTW, could the /api/v1/chat/attack/{id} return secret id?


I have successfully completed the attack on an old chat id, but I cannot see the secret id so cannot submit. . .

Retrieve a previous CHAT you created using its id.

**Comment by dedeswim** [comment]
Both changes will be online at 16 UTC (i.e., 37 minutes from now)

**Comment by dedeswim** [comment]
Both features are up and running now. Feel free to re-open if they don't work
