### ISSUE TITLE
OpenAI timeout when using Llama models

### ISSUE THREAD

**Issue by epistoteles** [ethz-spylab/satml-llms-ctf-issues#59]
The API is under heavy load right now. I'm trying to work on some Llama models.

However, it seems the API is doing some OpenAI requests in the background? At least I'm getting a 60 second OpenAI timeout error message.

Could you look into this and potentially remove OpenAI requests from Llama chats? This might free up some capacity.

**Comment by dedeswim** [comment]
From the Google Group [announcement](https://groups.google.com/g/satml-2024-llms-ctf/c/gvSlbEA2VLE) from yesterday:

> Our TogetherAI and OpenAI accounts have rate limits; there’s nothing we can do about this. If you start getting OpenAI errors (this is the error it will raise for both models, as we’re indirectly using `openai-python` for both) using the team budget tomorrow, try using your own keys.

**Comment by epistoteles** [comment]
Alright, thanks for the quick response!

**Comment by dpaleka** [comment]
It seems [TogetherAI upstream API](https://api.together.xyz/playground/chat/meta-llama/Llama-2-70b-chat-hf) is having issues. Can some participants try if it's also extremely slow for them too, on their personal keys?

**Comment by s-zanella** [comment]
I confirm that Together API is also unresponsive using paid tier keys.

**Comment by dedeswim** [comment]
We released an [announcement](https://groups.google.com/g/satml-2024-llms-ctf/c/sB0E0R6JKts). Please rereport any errors that are not covered by the announcement, thanks!

**Comment by dedeswim** [comment]
Looks like their API is up again

**Comment by dedeswim** [comment]
Looks like Together's API is having some issues again. We'll monitor the situation and act if the problem does not get solved soon.

**Comment by dedeswim** [comment]
Looks like the API is up again, closing but keeping pinned.

**Comment by dedeswim** [comment]
It seems to be up again?

**Comment by Sandr0x00** [comment]
Yep, only was down like 20-30min or so, luckily got up again :)
