### ISSUE TITLE
Some actions are steadily getting slower

### ISSUE THREAD

**Issue by dpaleka** [ethz-spylab/satml-llms-ctf-issues#61]
We've figured that creating new chats has been getting steadily slower since the peak, in a way that's not directly related to the overload. (There's also that factor, but it's slow even when there is a single active create chat request.) Working on a fix, hopefully less than 24 hours from now.

**Comment by dedeswim** [comment]
We should've solved this now through some better optimised DB queries. We'll leave it open for a while in case it becomes slower again.

As a reference, creating a chat went from taking >30s to taking <1s
