### ISSUE TITLE
Defenses Leaderboard tiebreaker

### ISSUE THREAD

**Issue by adrgs** [ethz-spylab/satml-llms-ctf-issues#62]
Could the leaderboard be updated such that it shows the correct order of the defenses given equal Value of Defense score?

Would help attacking teams determine on which defenses to focus next.

**Comment by dpaleka** [comment]
We can do the "sum of attacker scores" tiebreaker soon.
The timestamp tiebreaker is a bit too cumbersome in the leaderboard, sorry.

**Comment by dpaleka** [comment]
I guess this is done. We can produce a list of when defenses were first broken once every defense is broken and put it on the website; would this be a satisfactory solution?
