### ISSUE TITLE
meta/llama-2-70b-chat seems broken?

### ISSUE THREAD

**Issue by Sandr0x00** [ethz-spylab/satml-llms-ctf-issues#63]
In all my connections to meta/llama-2-70b-chat I get the following error: 

['OpenAI API error: A timeout error occurred. The function call took longer than 60 second(s).. If you have a team budget,note that your team budget has NOT been consumed.']

No matter if I use my own Together API key, or the team budget. It seems together.ai has some issues at the moment?

What happens with chats created now?

**Comment by dpaleka** [comment]
Oh TogetherAI... I checked https://api.together.xyz/playground/chat/meta-llama/Llama-2-70b-chat-hf and it doesn't work. Nothing we can do until they fix it.
I recommend stopping until the above link is working; last time they fixed it in a few hours.

Evaluation chats should still be there, you can check them using the API endpoints, read through https://ctf.spylab.ai/docs#/. Contact us if you think they are in the wrong state, meaning the message is recorded but you didn't get a reply, and you can't send consecutive attacker messages.

**Comment by Sandr0x00** [comment]
Works again.
