### ISSUE TITLE
Restart chat with same defense throws an error.

### ISSUE THREAD

**Issue by kejsitake** [ethz-spylab/satml-llms-ctf-issues#7]
Our team is having a problem with the restart chat functionality of the Interface.

Loading an existing defense works, but when trying to restart the chat with the same defense, we are getting this error on the top right corner: `Returned component textbox not specified as output of function.`

After this error, all text boxes also indicate an error, but no reason is given.

Is this a known issue? We could use this functionality earlier this week.

Thanks!

**Comment by dedeswim** [comment]
Hi, sorry for the inconvenience. The bug was introduced with the new feature we added to give defenses a name. This should be fixed now!
