### ISSUE TITLE
Creating Defense cannot specify name

### ISSUE THREAD

**Issue by KrystofM** [ethz-spylab/satml-llms-ctf-issues#9]
While creating a defense it is impossible to specficy the name of the defense. This can only be done with the rename endpoint right now, which is quite unconvinient.

**Comment by dedeswim** [comment]
Hi, thanks a lot for the suggestion. We'll add the feature asap!

**Comment by dedeswim** [comment]
It's now possible to do this via the API. We will add this to the interface as soon as possible

**Comment by dedeswim** [comment]
Hi! Unfortunately we didn't have time to do this because we had to work on more urgent fixes and on the development for the attack phase. We won't be adding this feature for this edition of the competition
